### ISSUE TITLE
Conda install fails with "Malformed version string '~' "

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#307]
* xclim version: 0.12.2  from conda-forge
* Python version: 3.7
* Operating System: Linux

### Description
Installation of xclim through conda fails because of the dependency specification in the conda recipe. `pip` accepts package specifications with `~= `, but conda doesn't and fails.

### What I Did

```
$  conda install -c conda-forge xclim
```

**Comment by Zeitsperre** [comment]
This doesn't seem to be a show-stopping issue for me when installing via miniconda3. In a fresh environment, everything seems to install fine (albeit with some warnings about flexible dependencies).

I think this is a combination of problems:
- @aulemahal and I confirmed that the tilde (~) is not allowed in the conda-forge recipe.yaml file, unlike in the Python setup.py. The equivalent way of writing `library~=0.10.0` would thus be ` library >=0.10.0,<0.11`
- The Anaconda on our internal servers needs to be updated in order to make use of newer features like flexible dependencies. It's possible that the builds have been passing on `xclim-feedstock` because of this feature.

@huard I can fix this in an update tonight if we want.

**Comment by huard** [comment]
Not a deal-breaker for me as long as travis-ci builds with the new release. Otherwise, the sooner this is fixed the better.

**Comment by Zeitsperre** [comment]
This should now be fixed via https://github.com/conda-forge/xclim-feedstock/pull/18. @aulemahal can you try re-installing xclim tomorrow or later this this week?

**Comment by Zeitsperre** [comment]
@huard The first potential source of the issue has been dealt with with the newest build on xclim on conda-forge. Tests today show that this problem persists for conda installations of xclim on our internal servers so it likely has to do with the Anaconda version.

@moulab88 could you try creating a test environment on our internal servers with system-installed anaconda and run `conda install -c conda-forge xclim`? If this bug is present for you, would it then be possible to perform an update of system installed conda?

**Comment by moulab88** [comment]
works on leto after update on base environnent:
conda update conda
You can test the new installation on py37_test env.

**Comment by Zeitsperre** [comment]
This issue seems to be fixed and has also resolved two bugs. If only this happened more often!
